FROM busybox
RUN mkdir -p /learningbase/train /learningbase/validation
COPY data/training_data.csv /tmp/learningbase/train/training_data.csv
COPY data/test_data.csv /tmp/learningbase/validation/test_data.csv
COPY Readme.md /Readme.md