FROM busybox
RUN mkdir -p /learningBase/train /learningBase/validation
COPY data/training_data.csv /learningBase/train/
COPY data/test_data.csv /learningBase/validation/
COPY Readme.md /learningBase/Readme.md