version: '3.9'
services:
  learning_base:
    image: learningbase_carpriceprediction
    container_name: learningbase_carpriceprediction
    volumes:
      - ai_system:/tmp
    command:
    - sh
    - "-c"
    - |
      rm -rf /tmp/learningBase/ && cp -r /learningBase/ /tmp/;
volumes:
  ai_system:
    external: true